# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
# Build the binary and put it into the builder image.
- name: gcr.io/cloud-builders/docker
  args:
  - build
  - --tag=${_IMAGE_PATH}
  - '.'
- name: gcr.io/cloud-builders/docker
  args:
  - push
  - ${_IMAGE_PATH}
- name: google/cloud-sdk
  args:
  - gcloud
  - run
  - deploy
  - --platform=managed
  - --region=europe-west3
  - ${_SERVICE_NAME}
  - --no-allow-unauthenticated
  - --image=${_IMAGE_PATH}
  - --no-allow-unauthenticated
  - --update-env-vars=CONFIG_PATH=${_CONFIG_PATH},PROJECT_ID=${PROJECT_ID}
substitutions:
  _IMAGE_PATH: logging-sample
  _SERVICE_NAME: googlechat-notifier
  _CONFIG_PATH: cloudbuild-notifier-config/config.yaml
 

